
package proxy;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "WeatherWS", targetNamespace = "http://ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WeatherWS {


    /**
     * 
     * @return
     *     returns java.util.List<proxy.City>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCities", targetNamespace = "http://ws/", className = "proxy.GetCities")
    @ResponseWrapper(localName = "getCitiesResponse", targetNamespace = "http://ws/", className = "proxy.GetCitiesResponse")
    @Action(input = "http://ws/WeatherWS/getCitiesRequest", output = "http://ws/WeatherWS/getCitiesResponse")
    public List<City> getCities();

    /**
     * 
     * @param cityId
     * @return
     *     returns proxy.City
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCity", targetNamespace = "http://ws/", className = "proxy.GetCity")
    @ResponseWrapper(localName = "getCityResponse", targetNamespace = "http://ws/", className = "proxy.GetCityResponse")
    @Action(input = "http://ws/WeatherWS/getCityRequest", output = "http://ws/WeatherWS/getCityResponse")
    public City getCity(
        @WebParam(name = "cityId", targetNamespace = "")
        int cityId);

    /**
     * 
     * @param temp
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "convert", targetNamespace = "http://ws/", className = "proxy.Convert")
    @ResponseWrapper(localName = "convertResponse", targetNamespace = "http://ws/", className = "proxy.ConvertResponse")
    @Action(input = "http://ws/WeatherWS/convertRequest", output = "http://ws/WeatherWS/convertResponse")
    public double convert(
        @WebParam(name = "temp", targetNamespace = "")
        Long temp);

}
